/**
 * Formats LLM generated content into clean, consistent Markdown.
 * Ensures documentation has proper structure, spacing, and metadata.
 */
export function formatDocumentation(rawContent, meta = {}) {
    const sha = meta.sha ? meta.sha.substring(0, 7) : "unknown";
    const repo = meta.repo || "unknown";

    // Clean/normalize LLM output
    const cleaned = (rawContent || "")
        .trim()
        .replace(/\n{3,}/g, "\n\n"); // prevent triple newlines

    return `
# 📘 Documentation Update for Commit \`${sha}\`

---

## 📝 Summary
Automatically generated documentation based on detected code modifications in commit **${sha}**.

---

## 📄 Detailed Documentation
${cleaned}

---

## 🗂 Metadata
- **Repository:** ${repo}
- **Commit:** ${sha}
- **Generated On:** ${new Date().toISOString()}
- **Generated By:** Documentation Sync Agent

---

> ⚠️ *This documentation was automatically created using code diffs and AI. Please review before publishing in production environments.*
`;
}
